# Generated by Django 5.0.4 on 2024-05-24 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=100)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('roomNo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('students_enrolled', models.PositiveBigIntegerField(default=0)),
                ('registration_deadline', models.TimeField(null=True)),
                ('deadline', models.TimeField(null=True)),
                ('prerequisites', models.ManyToManyField(blank=True, to='members.courses')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='members.courseschedule')),
            ],
        ),
        migrations.CreateModel(
            name='studentsRegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='members.courses')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='members.students')),
            ],
        ),
        migrations.AddField(
            model_name='students',
            name='courses',
            field=models.ManyToManyField(through='members.studentsRegs', to='members.courses'),
        ),
    ]
