# Generated by Django 5.0.4 on 2024-05-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_students_email_remove_students_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsregs',
            old_name='courseId',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentsregs',
            old_name='studentId',
            new_name='student',
        ),
    ]
