# Generated by Django 5.0.4 on 2024-05-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_courses_students_enrolled_students_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='registration_deadline',
            field=models.TimeField(null=True),
        ),
    ]
